[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "lix"
version = "0.1.1"
description = "LIX library for Lowell Instruments"
dependencies = [
    'gsw'
]